export const ProjectsData = [
  {
    id: 1,
    title: "Journey",
    subtitle: "",
    description: "",
    href: "https://github.com/LouisSleep/Journey",
    img: "",
    video: "",
  },
  {
    id: 2,
    title: "Fitness Park IOT",
    subtitle: "",
    description: "",
    href: "https://github.com/LouisSleep/iot-project",
    img: "",
    video: "",
  },
  {
    id: 3,
    title: "City GO",
    subtitle: "",
    description: "",
    href: "https://github.com/LouisSleep/citygo-app",
    img: "",
    video: "",
  },
  {
    id: 4,
    title: "BOARD",
    subtitle: "",
    description: "",
    href: "https://github.com/LouisSleep/board-dashboard-nextjs",
    img: "",
    video: "",
  },
];
